run_zad1:
	gcc -o zad1 zad1.c
	./zad1
	rm -f zad1

run_zad2:
	gcc -o zad2 zad2.c
	./zad2 4  
	rm -f zad2

test_zad2:
	gcc -o zad2 zad2.c
	./zad2 200
	./zad2 400
	./zad2 600
	./zad2 800
	./zad2 1000
	rm -f zad2

time_test_zad2:
	gcc -o zad2 zad2.c
	./zad2 100
	./zad2 200
	./zad2 300
	./zad2 400
	./zad2 500
	./zad2 600
	./zad2 700
	./zad2 800
	./zad2 900
	./zad2 1000
	rm -f zad2

run_zad3:
	gcc zad3.c -lm
	./a.out
	rm -f a.out

run_zad4:
	gcc zad4.c -lm
	./a.out 4
	rm -f a.out

time_test_zad4:
	gcc zad4.c -lm
	./a.out 100
	./a.out 200
	./a.out 300
	./a.out 400
	./a.out 500
	./a.out 600
	./a.out 700
	./a.out 800
	./a.out 900
	./a.out 1000
	rm -f a.out

clear:
	rm -f zad1 zad2 a.out